verbatim:
  cabal-version: 3.0

license: BSD-2-Clause
name: "solution-code"
version: 0
dependencies:
  - base
  - bytestring
  - base64-bytestring
  - containers
  - text
  - vector
  - time
  - unix
  - mtl
  - transformers
  - process

ghc-options:
  - -Wall

library:
  source-dirs: src
  ghc-options: -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - solution-code
