verbatim:
  cabal-version: 3.0

license: BSD-2-Clause
name: "chapter1-solutions"
version: 0
dependencies:
  - base

ghc-options:
  - -Wall

library:
  source-dirs: src
  ghc-options: -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - chapter1-solutions
